# Generated by Django 4.0.4 on 2022-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
